version: "3"
services:
  mautic:
    image: mayeu/mautic
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
      MAUTIC_MAILER_FROM_NAME: 'Mailer name'
      MAUTIC_MAILER_FROM_EMAIL: 'root@example.org'
      MAUTIC_MAILER_SMTP_HOST: test
      MAUTIC_MAILER_SMTP_PASSWORD: test
      MAUTIC_SITE_URL: http://localhost:8080
    volumes:
      - "./mautic-local:/var/www/html/app/local"
  mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
