<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'mysql',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'mautic',
	'db_password' => 'mauticdbpass',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.5.5-10.3.10-MariaDB-1:10.3.10+maria~bionic',
	'mailer_from_name' => 'root root',
	'mailer_from_email' => 'root@example.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => 'test',
	'mailer_port' => '586',
	'mailer_user' => 'lol',
	'mailer_password' => 'lol',
	'mailer_encryption' => 'tls',
	'mailer_auth_mode' => 'plain',
	'mailer_spool_type' => 'file',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '85d8a558c742bfe54f60c115c973373cdbdda7f72914b7e908d5478f7ede1a2a',
	'site_url' => 'http://localhost:8080',
);
